# So we get Ubuntu Trusty - using "dist: trusty" breaks OS X.
services: docker

os:
  - linux
  - osx


env:
  global:
    - PATH=/home/travis/bin:/home/travis/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  matrix:
    - TESTENV=py35 XVFB=1 INSTALL_PYQT=1
    - TESTENV=py34 XVFB=1 INSTALL_PYQT=1
    - TESTENV=unittests-nodisp XVFB=0 INSTALL_PYQT=1
    - TESTENV=misc XVFB=0 INSTALL_PYQT=0
    - TESTENV=pep257 XVFB=0 INSTALL_PYQT=0
    - TESTENV=pyflakes XVFB=0 INSTALL_PYQT=0
    - TESTENV=pep8 XVFB=0 INSTALL_PYQT=0
    - TESTENV=mccabe XVFB=0 INSTALL_PYQT=0
    - TESTENV=pyroma XVFB=0 INSTALL_PYQT=0
    - TESTENV=check-manifest XVFB=0 INSTALL_PYQT=0
    - TESTENV=pylint ON_OS=linux XVFB=0 INSTALL_PYQT=1

# Not really, but this is here so we can do stuff by hand.
language: c

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/build/The-Compiler/qutebrowser/.cache

install:
  - python scripts/dev/ci_install.py

script:
  - python scripts/dev/ci_run.py

matrix:
  exclude:
    - os: linux
      env: TESTENV=py35 XVFB=1 INSTALL_PYQT=1
    - os: osx
      env: TESTENV=py34 XVFB=1 INSTALL_PYQT=1
    - os: osx
      env: TESTENV=unittests-nodisp XVFB=0 INSTALL_PYQT=1
    - os: osx
      env: TESTENV=misc XVFB=0 INSTALL_PYQT=0
    - os: osx
      env: TESTENV=pep257 XVFB=0 INSTALL_PYQT=0
    - os: osx
      env: TESTENV=pyflakes XVFB=0 INSTALL_PYQT=0
    - os: osx
      env: TESTENV=pep8 XVFB=0 INSTALL_PYQT=0
    - os: osx
      env: TESTENV=mccabe XVFB=0 INSTALL_PYQT=0
    - os: osx
      env: TESTENV=pyroma XVFB=0 INSTALL_PYQT=0
    - os: osx
      env: TESTENV=check-manifest XVFB=0 INSTALL_PYQT=0
    - os: osx
      env: env TESTENV=pylint ON_OS=linux XVFB=0 INSTALL_PYQT=1
